[package]
name = "wait-for-net"
version = "0.1.0"
edition = "2021"

[dependencies]
libroute = { path = "../libroute" }
lazy_static = "1.4.0"
thiserror = "1.0.57"
env_logger = "0.11.2"
clap = { version = "4.5.1", features = ["derive"] }
timeout-readwrite = "0.3.3"
log = "0.4.20"
